### Get all todos
GET {{localhost}}:{{port}}/api/todo

### Get todo by id
GET {{localhost}}:{{port}}/api/todo/{{id}}

### Add todo
POST {{localhost}}:{{port}}/api/todo
Content-Type: application/json

{
  "description": "my todo",
  "status": "OPEN"
}

> {%
    var res = response.body
    client.global.set("id", res.id)
%}